# Generated by Django 4.0.4 on 2023-08-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_payment_status_alter_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('PAID', 'PAID')], max_length=8),
        ),
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('PAYMENT', 'PAYMENT'), ('FINE', 'FINE')], max_length=8),
        ),
    ]
