# Generated by Django 4.0.4 on 2023-08-14 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0002_borrowing_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowing',
            name='is_active',
        ),
    ]
