# Generated by Django 4.2.4 on 2023-08-14 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0002_alter_book_cover"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="cover",
            field=models.CharField(
                choices=[("HARD", "Hard cover"), ("SOFT", "Soft cover")], max_length=10
            ),
        ),
    ]
