# Generated by Django 4.2.4 on 2023-08-14 20:49

import book.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0003_alter_book_cover"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="image",
            field=models.ImageField(
                null=True, upload_to=book.models.movie_image_file_path
            ),
        ),
    ]
