# Generated by Django 4.2.4 on 2023-08-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="telegram_nick",
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
